version: "4.5"

services:
  verification-service:
    container_name: verification-service
    build:
      context: .
    env_file:
      - .env.prod
    environment:
      WAIT_HOSTS: verf-postgres:5432
    depends_on:
      - verf-postgres
    ports:
      - "5254:5254"

  verf-postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    ports:
      - "5438:5434"

volumes:
  pgdata: