version: '3.9'
services:
  gateway:
    build:
      context: .
    container_name: 'gateway'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:${HTTP_PORT}"
      - "8081:9001"