version: "4.5"

services:
  file-service:
    container_name: file-service
    build:
      context: .
    env_file:
      - .env.prod
    depends_on:
      - minio
    ports:
      - "5253:5253"

  minio:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.minio
    command: server /data --console-address ":9001"


volumes:
  data: