version: "3"

services:

  minio:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.minio
    command: server /data --console-address ":9001"


volumes:
  data: