version: '4.5'
services:
  auth-service:
    container_name: auth-service
    build:
      context: .
    env_file:
      - .env.prod
    environment:
      WAIT_HOSTS: auth-postgres:5432, auth-redis:6379
    depends_on:
      - auth-postgres
      - auth-redis
    ports:
      - "5252:5252"

  auth-postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    ports:
      - "5432:5432"

  auth-redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env.redis
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

