// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: universities.proto

package universities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PanoramaTypes int32

const (
	PanoramaTypes_Buildings   PanoramaTypes = 0
	PanoramaTypes_Dormitories PanoramaTypes = 1
	PanoramaTypes_Canteens    PanoramaTypes = 2
	PanoramaTypes_Other       PanoramaTypes = 3
)

// Enum value maps for PanoramaTypes.
var (
	PanoramaTypes_name = map[int32]string{
		0: "Buildings",
		1: "Dormitories",
		2: "Canteens",
		3: "Other",
	}
	PanoramaTypes_value = map[string]int32{
		"Buildings":   0,
		"Dormitories": 1,
		"Canteens":    2,
		"Other":       3,
	}
)

func (x PanoramaTypes) Enum() *PanoramaTypes {
	p := new(PanoramaTypes)
	*p = x
	return p
}

func (x PanoramaTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PanoramaTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_universities_proto_enumTypes[0].Descriptor()
}

func (PanoramaTypes) Type() protoreflect.EnumType {
	return &file_universities_proto_enumTypes[0]
}

func (x PanoramaTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PanoramaTypes.Descriptor instead.
func (PanoramaTypes) EnumDescriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{0}
}

type UniversityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UniversityId) Reset() {
	*x = UniversityId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversityId) ProtoMessage() {}

func (x *UniversityId) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversityId.ProtoReflect.Descriptor instead.
func (*UniversityId) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{0}
}

func (x *UniversityId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OpenDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityName string `protobuf:"bytes,1,opt,name=universityName,proto3" json:"universityName,omitempty"`
	Description    string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address        string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Link           string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Time           int64  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OpenDay) Reset() {
	*x = OpenDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDay) ProtoMessage() {}

func (x *OpenDay) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDay.ProtoReflect.Descriptor instead.
func (*OpenDay) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{1}
}

func (x *OpenDay) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *OpenDay) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OpenDay) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OpenDay) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *OpenDay) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type OpenDays struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days []*OpenDay `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
}

func (x *OpenDays) Reset() {
	*x = OpenDays{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDays) ProtoMessage() {}

func (x *OpenDays) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDays.ProtoReflect.Descriptor instead.
func (*OpenDays) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{2}
}

func (x *OpenDays) GetDays() []*OpenDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{3}
}

func (x *Params) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Params) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityId string  `protobuf:"bytes,1,opt,name=universityId,proto3" json:"universityId,omitempty"`
	Params       *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewsRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *GetReviewsRequest) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityId string `protobuf:"bytes,1,opt,name=universityId,proto3" json:"universityId,omitempty"`
	AuthorStatus string `protobuf:"bytes,2,opt,name=authorStatus,proto3" json:"authorStatus,omitempty"`
	Sentiment    string `protobuf:"bytes,3,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	Date         int64  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Text         string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	RepliesCount int32  `protobuf:"varint,6,opt,name=repliesCount,proto3" json:"repliesCount,omitempty"`
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{5}
}

func (x *Review) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *Review) GetAuthorStatus() string {
	if x != nil {
		return x.AuthorStatus
	}
	return ""
}

func (x *Review) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *Review) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Review) GetRepliesCount() int32 {
	if x != nil {
		return x.RepliesCount
	}
	return 0
}

type Reviews struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reviews []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
}

func (x *Reviews) Reset() {
	*x = Reviews{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reviews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reviews) ProtoMessage() {}

func (x *Reviews) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reviews.ProtoReflect.Descriptor instead.
func (*Reviews) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{6}
}

func (x *Reviews) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type Panorama struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityId   string        `protobuf:"bytes,1,opt,name=universityId,proto3" json:"universityId,omitempty"`
	Address        string        `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name           string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FirstLocation  string        `protobuf:"bytes,4,opt,name=firstLocation,proto3" json:"firstLocation,omitempty"`
	SecondLocation string        `protobuf:"bytes,5,opt,name=secondLocation,proto3" json:"secondLocation,omitempty"`
	Type           PanoramaTypes `protobuf:"varint,6,opt,name=type,proto3,enum=universities.PanoramaTypes" json:"type,omitempty"`
}

func (x *Panorama) Reset() {
	*x = Panorama{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Panorama) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panorama) ProtoMessage() {}

func (x *Panorama) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panorama.ProtoReflect.Descriptor instead.
func (*Panorama) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{7}
}

func (x *Panorama) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *Panorama) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Panorama) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Panorama) GetFirstLocation() string {
	if x != nil {
		return x.FirstLocation
	}
	return ""
}

func (x *Panorama) GetSecondLocation() string {
	if x != nil {
		return x.SecondLocation
	}
	return ""
}

func (x *Panorama) GetType() PanoramaTypes {
	if x != nil {
		return x.Type
	}
	return PanoramaTypes_Buildings
}

type Panoramas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panoramas []*Panorama `protobuf:"bytes,1,rep,name=panoramas,proto3" json:"panoramas,omitempty"`
}

func (x *Panoramas) Reset() {
	*x = Panoramas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Panoramas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panoramas) ProtoMessage() {}

func (x *Panoramas) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panoramas.ProtoReflect.Descriptor instead.
func (*Panoramas) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{8}
}

func (x *Panoramas) GetPanoramas() []*Panorama {
	if x != nil {
		return x.Panoramas
	}
	return nil
}

type CreatePanoramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panorama *Panorama `protobuf:"bytes,1,opt,name=panorama,proto3" json:"panorama,omitempty"`
}

func (x *CreatePanoramaRequest) Reset() {
	*x = CreatePanoramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePanoramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePanoramaRequest) ProtoMessage() {}

func (x *CreatePanoramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePanoramaRequest.ProtoReflect.Descriptor instead.
func (*CreatePanoramaRequest) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePanoramaRequest) GetPanorama() *Panorama {
	if x != nil {
		return x.Panorama
	}
	return nil
}

type GetPanoramasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityId string `protobuf:"bytes,1,opt,name=universityId,proto3" json:"universityId,omitempty"`
	Category     string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *GetPanoramasRequest) Reset() {
	*x = GetPanoramasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPanoramasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPanoramasRequest) ProtoMessage() {}

func (x *GetPanoramasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPanoramasRequest.ProtoReflect.Descriptor instead.
func (*GetPanoramasRequest) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{10}
}

func (x *GetPanoramasRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *GetPanoramasRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type University struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LongName     string  `protobuf:"bytes,3,opt,name=longName,proto3" json:"longName,omitempty"`
	Logo         string  `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Rating       float32 `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Region       string  `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Type         string  `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	StudyFields  int32   `protobuf:"varint,8,opt,name=studyFields,proto3" json:"studyFields,omitempty"`
	BudgetPlaces int32   `protobuf:"varint,9,opt,name=budgetPlaces,proto3" json:"budgetPlaces,omitempty"`
}

func (x *University) Reset() {
	*x = University{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{11}
}

func (x *University) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *University) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *University) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *University) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *University) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *University) GetStudyFields() int32 {
	if x != nil {
		return x.StudyFields
	}
	return 0
}

func (x *University) GetBudgetPlaces() int32 {
	if x != nil {
		return x.BudgetPlaces
	}
	return 0
}

type UniversitiesSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Universities []*University `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
}

func (x *UniversitiesSchema) Reset() {
	*x = UniversitiesSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversitiesSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversitiesSchema) ProtoMessage() {}

func (x *UniversitiesSchema) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversitiesSchema.ProtoReflect.Descriptor instead.
func (*UniversitiesSchema) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{12}
}

func (x *UniversitiesSchema) GetUniversities() []*University {
	if x != nil {
		return x.Universities
	}
	return nil
}

type PageParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PageParams) Reset() {
	*x = PageParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageParams) ProtoMessage() {}

func (x *PageParams) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageParams.ProtoReflect.Descriptor instead.
func (*PageParams) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{13}
}

func (x *PageParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PageParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUniversitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchUniversitiesRequest) Reset() {
	*x = SearchUniversitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUniversitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUniversitiesRequest) ProtoMessage() {}

func (x *SearchUniversitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUniversitiesRequest.ProtoReflect.Descriptor instead.
func (*SearchUniversitiesRequest) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{14}
}

func (x *SearchUniversitiesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTopOfUniversitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetTopOfUniversitiesRequest) Reset() {
	*x = GetTopOfUniversitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopOfUniversitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopOfUniversitiesRequest) ProtoMessage() {}

func (x *GetTopOfUniversitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopOfUniversitiesRequest.ProtoReflect.Descriptor instead.
func (*GetTopOfUniversitiesRequest) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{15}
}

func (x *GetTopOfUniversitiesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_universities_proto protoreflect.FileDescriptor

var file_universities_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x12, 0x26,
	0x0a, 0x0e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x08, 0x4f, 0x70,
	0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x04, 0x64, 0x61, 0x79,
	0x73, 0x22, 0x36, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x65, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0xba, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x22, 0x0a, 0x0c, 0x75,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x39, 0x0a,
	0x07, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52,
	0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x6e,
	0x6f, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a,
	0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x41, 0x0a, 0x09, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61,
	0x6d, 0x61, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x09,
	0x70, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x73, 0x22, 0x4b, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x08, 0x70, 0x61,
	0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x22, 0x55, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6e,
	0x6f, 0x72, 0x61, 0x6d, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xea, 0x01,
	0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x79, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x12, 0x55, 0x6e,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x3c, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x52, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x3a,
	0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x2f, 0x0a, 0x19, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x4f, 0x66, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2a, 0x48, 0x0a, 0x0d, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x61, 0x6e, 0x74, 0x65, 0x65, 0x6e, 0x73, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x03, 0x32, 0x8e, 0x05, 0x0a, 0x0c, 0x55,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1a, 0x2e, 0x75, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x44,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1f, 0x2e, 0x75,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x4d, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x23, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x6e, 0x6f,
	0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x6e,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x6e, 0x6f, 0x72,
	0x61, 0x6d, 0x61, 0x12, 0x4a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61,
	0x6d, 0x61, 0x73, 0x12, 0x21, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x73, 0x12,
	0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x12, 0x1a, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x18, 0x2e, 0x75,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x12, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x1a, 0x20, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x5f, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x2e, 0x75, 0x6e,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x63, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x4f, 0x66, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x29,
	0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x4f, 0x66, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x12, 0x5a, 0x10, 0x61,
	0x70, 0x69, 0x2f, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_universities_proto_rawDescOnce sync.Once
	file_universities_proto_rawDescData = file_universities_proto_rawDesc
)

func file_universities_proto_rawDescGZIP() []byte {
	file_universities_proto_rawDescOnce.Do(func() {
		file_universities_proto_rawDescData = protoimpl.X.CompressGZIP(file_universities_proto_rawDescData)
	})
	return file_universities_proto_rawDescData
}

var file_universities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_universities_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_universities_proto_goTypes = []interface{}{
	(PanoramaTypes)(0),                  // 0: universities.PanoramaTypes
	(*UniversityId)(nil),                // 1: universities.UniversityId
	(*OpenDay)(nil),                     // 2: universities.OpenDay
	(*OpenDays)(nil),                    // 3: universities.OpenDays
	(*Params)(nil),                      // 4: universities.Params
	(*GetReviewsRequest)(nil),           // 5: universities.GetReviewsRequest
	(*Review)(nil),                      // 6: universities.Review
	(*Reviews)(nil),                     // 7: universities.Reviews
	(*Panorama)(nil),                    // 8: universities.Panorama
	(*Panoramas)(nil),                   // 9: universities.Panoramas
	(*CreatePanoramaRequest)(nil),       // 10: universities.CreatePanoramaRequest
	(*GetPanoramasRequest)(nil),         // 11: universities.GetPanoramasRequest
	(*University)(nil),                  // 12: universities.University
	(*UniversitiesSchema)(nil),          // 13: universities.UniversitiesSchema
	(*PageParams)(nil),                  // 14: universities.PageParams
	(*SearchUniversitiesRequest)(nil),   // 15: universities.SearchUniversitiesRequest
	(*GetTopOfUniversitiesRequest)(nil), // 16: universities.GetTopOfUniversitiesRequest
}
var file_universities_proto_depIdxs = []int32{
	2,  // 0: universities.OpenDays.days:type_name -> universities.OpenDay
	4,  // 1: universities.GetReviewsRequest.params:type_name -> universities.Params
	6,  // 2: universities.Reviews.reviews:type_name -> universities.Review
	0,  // 3: universities.Panorama.type:type_name -> universities.PanoramaTypes
	8,  // 4: universities.Panoramas.panoramas:type_name -> universities.Panorama
	8,  // 5: universities.CreatePanoramaRequest.panorama:type_name -> universities.Panorama
	12, // 6: universities.UniversitiesSchema.universities:type_name -> universities.University
	1,  // 7: universities.Universities.GetOpenDays:input_type -> universities.UniversityId
	5,  // 8: universities.Universities.GetReviews:input_type -> universities.GetReviewsRequest
	10, // 9: universities.Universities.CreatePanorama:input_type -> universities.CreatePanoramaRequest
	11, // 10: universities.Universities.GetPanoramas:input_type -> universities.GetPanoramasRequest
	1,  // 11: universities.Universities.GetUniversity:input_type -> universities.UniversityId
	14, // 12: universities.Universities.GetUniversities:input_type -> universities.PageParams
	15, // 13: universities.Universities.SearchUniversities:input_type -> universities.SearchUniversitiesRequest
	16, // 14: universities.Universities.GetTopOfUniversities:input_type -> universities.GetTopOfUniversitiesRequest
	3,  // 15: universities.Universities.GetOpenDays:output_type -> universities.OpenDays
	7,  // 16: universities.Universities.GetReviews:output_type -> universities.Reviews
	8,  // 17: universities.Universities.CreatePanorama:output_type -> universities.Panorama
	9,  // 18: universities.Universities.GetPanoramas:output_type -> universities.Panoramas
	12, // 19: universities.Universities.GetUniversity:output_type -> universities.University
	13, // 20: universities.Universities.GetUniversities:output_type -> universities.UniversitiesSchema
	13, // 21: universities.Universities.SearchUniversities:output_type -> universities.UniversitiesSchema
	13, // 22: universities.Universities.GetTopOfUniversities:output_type -> universities.UniversitiesSchema
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_universities_proto_init() }
func file_universities_proto_init() {
	if File_universities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_universities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversityId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDays); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReviewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reviews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Panorama); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Panoramas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePanoramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPanoramasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*University); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversitiesSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUniversitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopOfUniversitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_universities_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_universities_proto_goTypes,
		DependencyIndexes: file_universities_proto_depIdxs,
		EnumInfos:         file_universities_proto_enumTypes,
		MessageInfos:      file_universities_proto_msgTypes,
	}.Build()
	File_universities_proto = out.File
	file_universities_proto_rawDesc = nil
	file_universities_proto_goTypes = nil
	file_universities_proto_depIdxs = nil
}
