// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"time"
)

type University struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	LongName string `json:"long_name"`
	Logo     string `json:"logo"`
}

type UniversityOpenDay struct {
	UniversityID string    `json:"university_id"`
	Description  string    `json:"description"`
	Date         time.Time `json:"date"`
	Address      string    `json:"address"`
	Link         string    `json:"link"`
}

type UniversityOwner struct {
	UniversityID string `json:"university_id"`
	UserID       string `json:"user_id"`
}
