// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: universities.proto

package universities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniversityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UniversityId) Reset() {
	*x = UniversityId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversityId) ProtoMessage() {}

func (x *UniversityId) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversityId.ProtoReflect.Descriptor instead.
func (*UniversityId) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{0}
}

func (x *UniversityId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OpenDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniversityName string `protobuf:"bytes,1,opt,name=universityName,proto3" json:"universityName,omitempty"`
	Description    string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address        string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Link           string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Time           int64  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OpenDay) Reset() {
	*x = OpenDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDay) ProtoMessage() {}

func (x *OpenDay) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDay.ProtoReflect.Descriptor instead.
func (*OpenDay) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{1}
}

func (x *OpenDay) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *OpenDay) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OpenDay) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OpenDay) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *OpenDay) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type OpenDays struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days []*OpenDay `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
}

func (x *OpenDays) Reset() {
	*x = OpenDays{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDays) ProtoMessage() {}

func (x *OpenDays) ProtoReflect() protoreflect.Message {
	mi := &file_universities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDays.ProtoReflect.Descriptor instead.
func (*OpenDays) Descriptor() ([]byte, []int) {
	return file_universities_proto_rawDescGZIP(), []int{2}
}

func (x *OpenDays) GetDays() []*OpenDay {
	if x != nil {
		return x.Days
	}
	return nil
}

var File_universities_proto protoreflect.FileDescriptor

var file_universities_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x12, 0x26,
	0x0a, 0x0e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x08, 0x4f, 0x70,
	0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x04, 0x64, 0x61, 0x79,
	0x73, 0x32, 0x51, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x41, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73,
	0x12, 0x1a, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x75,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x44, 0x61, 0x79, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_universities_proto_rawDescOnce sync.Once
	file_universities_proto_rawDescData = file_universities_proto_rawDesc
)

func file_universities_proto_rawDescGZIP() []byte {
	file_universities_proto_rawDescOnce.Do(func() {
		file_universities_proto_rawDescData = protoimpl.X.CompressGZIP(file_universities_proto_rawDescData)
	})
	return file_universities_proto_rawDescData
}

var file_universities_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_universities_proto_goTypes = []interface{}{
	(*UniversityId)(nil), // 0: universities.UniversityId
	(*OpenDay)(nil),      // 1: universities.OpenDay
	(*OpenDays)(nil),     // 2: universities.OpenDays
}
var file_universities_proto_depIdxs = []int32{
	1, // 0: universities.OpenDays.days:type_name -> universities.OpenDay
	0, // 1: universities.Universities.GetOpenDays:input_type -> universities.UniversityId
	2, // 2: universities.Universities.GetOpenDays:output_type -> universities.OpenDays
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_universities_proto_init() }
func file_universities_proto_init() {
	if File_universities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_universities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversityId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDays); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_universities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_universities_proto_goTypes,
		DependencyIndexes: file_universities_proto_depIdxs,
		MessageInfos:      file_universities_proto_msgTypes,
	}.Build()
	File_universities_proto = out.File
	file_universities_proto_rawDesc = nil
	file_universities_proto_goTypes = nil
	file_universities_proto_depIdxs = nil
}
