version: "4.5"

services:
  students-service:
    container_name: students-service
    build:
      context: .
    env_file:
      - .env.prod
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    ports:
      - "5254:5254"

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    ports:
      - "5433:5432"

volumes:
  pgdata: